version: '3'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./db/conf.d/:/etc/mysql/conf.d
      - ./db/data/:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    env_file:
      - ./db/.env